components:
  - name: component1
    type: XYZ99999
    settings:
      username: HONGQI9999
      country: canada
      address: oakcrest
      telephone: 999-999-9999
      zipcode: k4a0l4
      city: ottawa
