daemonalloc:
  abc: xyz
components:
  - name: component1
    type: XYZ99999
    settings:
      username: HONGQI9999
      country: canada
      address: oakcrest
      phone: 999-999-9999
      zip: k4a 0l4
    addon: ppp
    addin: qqq
