components:
  - !component
    name: component1
    argv: xyz
    settings:
      username: hongqi9999
      password: nopass
  - !component
    name: component2
    argv1: first2
    settings:
      username: hongqi3333
      password: pass333333
