components:
  - !component
    name: component1
    type: xyz
    settings:
        username: hongqi9999
  - !component
    name: component2
    type: xyz
    settings:
        address: oakcrest     
  - !component
    name: component3
    type: xyz
    settings:
        telephone: 999-999-9999
  - !component
    name: component4
    type: xyz
    settings:
        zipcode: k4a0l4        
        city: ottawa   
 